apiVersion: v1
kind: Pod
metadata:
  name: init-konteyner
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - name: workdir
      mountPath: /usr/share/nginx/html
  initContainers:
  - name: hazirlik
    image: busybox
    command:
    - wget
    - "-O"
    - "/work-dir/index.html"
    - https://raw.githubusercontent.com/enterprisecoding-ltd/k8s-ornekleri/master/pod/ornek-index.html
    volumeMounts:
    - name: workdir
      mountPath: "/work-dir"
  dnsPolicy: Default
  volumes:
  - name: workdir
    emptyDir: {}