apiVersion: v1
kind: Pod
metadata:
  name: restart-politikasi
spec:
  containers:
  - name: shell
    image: busybox
    command: ['sh', '-c', 'echo "Merhaba, Kubernetes!" && exit -1']
  restartPolicy: Never