apiVersion: v1
kind: ResourceQuota
metadata:
  name: nesne-sayilari
  namespace: kota-calismasi
spec:
  hard:
    configmaps: "10"
    persistentvolumeclaims: "4"
    pods: "4"
    replicationcontrollers: "20"
    secrets: "10"
    services: "10"