apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ilk-statefulset
  labels:
    app: k8sornek
spec:
  replicas: 3
  serviceName: "k8sornek"
  selector:
    matchLabels:
      app: k8sornek
  template:
    metadata:
      labels:
        app: k8sornek
    spec:
      containers:
      - name: uygulama
        image: enterprisecodingcom/k8sornek
        ports:
        - containerPort: 80