apiVersion: v1
kind: Pod 
metadata: 
  name: http-server-istemci
spec:
  containers:
  - name: curl
    image: appropriate/curl
    command: ["/bin/sh"]
    args: ["-c","curl http-server-service:4000 "]