apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: basarili-gecmis-limit
spec:
  schedule: "*/1 * * * *"
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: basarili-gecmis-limit-konteyner
            image: busybox
            command: ["echo", "Zamanlanmış iş çalışıyor.."]
          restartPolicy: OnFailure