apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: eszamanli-izin-verilen
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: Allow
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: cronjob
              image: busybox
              args:
                - /bin/sh
                - -c
                - date; echo 90 saniyeliğine uyunuyor....; sleep 90s; echo sonlanıyor...;
          restartPolicy: Never