apiVersion: v1
kind: Pod
metadata:
  name: pod-secret
spec:
  containers:
  - name: pod-secret
    image: busybox
    args:
    - sleep
    - "86400"
    volumeMounts:
    - name: sifre
      mountPath: /sirlar
      readOnly: true
  volumes:
  - name: sifre
    secret:
      secretName: sifre