apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-stratejisi
  labels:
    app: k8sornek
spec:
  revisionHistoryLimit: 10
  replicas: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: k8sornek
  template:
    metadata:
      labels:
        app: k8sornek
    spec:
      containers:
      - name: uygulama
        image: enterprisecodingcom/k8sornek
        ports:
        - containerPort: 80