apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ilk-ingress
spec:
  rules:
  - host: "v1.k8s.localhost"
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: uygulama-servisi-v1
            port:
              number: 80
  - host: "v2.k8s.localhost"
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: uygulama-servisi-v2
            port:
              number: 80