apiVersion: networking.k8s.io/v1 
kind: Ingress
metadata:
  name: ilk-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /v1
        pathType: Prefix
        backend:
          service:
            name: uygulama-servisi-v1
            port: 
              number: 80
  - http:
      paths:
      - path: /v2
        pathType: Prefix
        backend:
          service:
            name: uygulama-servisi-v2
            port: 
              number: 80
