apiVersion: apps/v1
kind: Deployment
metadata:
  name: ornek-uygulama
  namespace: test
  labels:
    app: k8sornek
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8sornek
  template:
    metadata:
      labels:
        app: k8sornek
    spec:
      containers:
      - name: uygulama
        image: enterprisecodingcom/k8sornek
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: uygulama-servisi
  namespace: test
  labels:
    app: k8sornek
spec:
  selector:
    app: k8sornek
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
